version: '3.8'
services:
  python3:
    restart: always
    build: 
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: 'Docker_python'
    working_dir: '/usr/src/app'
    tty: true
    volumes:
      - ../src:/usr/src/app
